### ISSUE TITLE
iSu deletes SU if deactivated upon reboot

### ISSUE THREAD

**Issue by JaredTamana** [bhb27/isu#12]
When rebooting/powering off, iSu won't reactivate SU and will delete the /system/bin/SU and /system/xbin/SU files, requiring the user to reflash the binaries. 

Nexus 5X (bullhead)
Hexa ROM

**Comment by fgl27** [comment]
That is only a problem on Nougat, is intended to delete bin/su, xbin/su is there hide but the service that restore it was broke...

if the problem is not on nougat let me know, if is use latest V4.8.

**Comment by JaredTamana** [comment]
Have you been able to figure out what's changed in Nougat to cause this?

**Comment by fgl27** [comment]
Not exactly, was a selinux related polices that was changed, but I did not look were, as I can't fix that without change the ROM source, I made a change to what I can with is the app...
